package com.neo.drools.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckGit implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CheckGit() {
	System.err.println("Temp");


System.err.println("Temp");


System.err.println("Temp");

System.err.println("Temp");
System.err.println("Temp");

System.err.println("Temp");
System.out.println("Temp");

    }




}